sudo: false
language: node_js
node_js:
  - 4
  - 5
  - 6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=units
    - TEST_SUITE=end-to-end
script: npm run $TEST_SUITE
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
before_script:
  - npm prune
